# Generated by Django 5.1.5 on 2026-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ganancia',
            field=models.IntegerField(default=0),
        ),
    ]
