# Generated by Django 5.1.5 on 2026-04-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pago',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.FloatField(default=0),
        ),
    ]
