# Generated by Django 5.1.5 on 2026-05-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_codigo'),
        ('ventas', '0004_venta_pago_venta_tipo_pago_venta_vuelto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('estado', models.CharField(default='abierta', max_length=10)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.negocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
