# Generated by Django 5.1.5 on 2026-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='timbrado',
            field=models.CharField(default='12345678', max_length=50),
        ),
    ]
