# Generated by Django 5.1.5 on 2026-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_numero_factura_venta_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
