# Generated by Django 5.1.5 on 2026-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_compra_detallecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
