# Generated by Django 5.1.5 on 2026-06-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AddField(
            model_name='negocio',
            name='punto_expedicion',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AddField(
            model_name='negocio',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='timbrado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
